### ISSUE TITLE
conversation.say doesn't output until you end the convo

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1045] opened 2017-09-19 12:18 UTC
I'm not sure if this is a bug or expected behavior, but it makes conversations much less useful.

Could we add a conversation.flush() method to output queued messages without ending the conversation?

I guess I can use bot.say() in these cases, but the conversation methods don't get a passed a reference to the bot (?) so I'd have to store/pass that around.

Use case:
If I have a conversation and in the middle I want to add a response, eg to a 'hint' or clarification if the user doesn't give an expected answer, there's no way to use bot.say without ending the whole conversation.

consider the snippet below

in this case if the user enters hint
I can try to convo.say("Rhymes with foo!");
but this will NOT output until I fire a convo.next()
doing that will however end the conversation.

I also tried with convo.repeat() and silentRepeat() but these seem to not behave as expected.

ConvoTest.start = function (bot, message) {
    debug("message", message);
    bot.startConversation(message, function (err, convo) {
        if (err) {
            console.log("err", err);
            return;
        }
        convo.say("Start single player game");
        // convo.ask("What color is the sky?", ConvoTest.quizQuestion);
        convo.ask("What color is the sky?", ConvoTest.multiResponse);

        convo.on('end', function (convo) {
            bot.say({
                text: "Game Over",
                channel: message.user
            });
            // convo.say("Done!");
            // convo.next();
            if(convo.status === 'completed') {
                console.log("end convo");
            }
        });

    });

};

ConvoTest.multiResponse = [
    {
        pattern: /hint/,
        callback: function (response, convo) {
            convo.say("Rhymes with foo!");
            // FIXME - this will exit the conversation
            // but without it, nothing is output
            convo.next();
        }
    },

    {
        pattern: /what/,
        callback: function (response, convo) {
            convo.say("Say what?");
            convo.repeat();
            convo.next();
        }
    },
    {
        pattern: /blue/,
        callback: function (response, convo) {
            convo.say("yes, you win!");
            convo.next();
        }
    },
    {
        default: true,
        callback: function(response, convo) {
            convo.say("no, try again");
            // convo.repeat();
            convo.silentRepeat();
            convo.next();
        }
    }
];

**Comment by benbrown** [comment] 2017-09-19 14:46
@Yulgana33 I'm not sure what you are attempting to do here - this is (once again) a duplicate of an existing issue that already has a lot of helpful discussion attached to it.  

Please DO NOT create duplicate issues, it is a big drain on our limited resources.

**Closed by benbrown** 2017-09-19 14:46 UTC
Labels: question

**Comment by peterswimm** [comment] 2017-09-19 14:58
https://github.com/howdyai/botkit/issues/318
