### ISSUE TITLE
Duplicate message when using replyPublic.

### ISSUE THREAD

**Issue by ShaneHowell** [howdyai/botkit#595] opened 2017-01-12 22:17 UTC
I've been using botkit for a while now but only in the replyPrivate method, i'm in the process of adding in another Slash Command to the bot where the response is public but i'm running into an issue where the message is duplicated: the original message and then the response. 

<img width="221" alt="screen shot 2017-01-12 at 4 49 50 pm" src="https://cloud.githubusercontent.com/assets/5295741/21909828/8b84eb6a-d8e7-11e6-96a1-526f32b3ce86.png">

Is there a way to prevent the user input from showing up in Slack when using replyPublic like replyPrivate does?

Here's what i'm working with:
```
controller.on('slash_command', function (slashCommand, message) {
   switch (message.command) {
      case '/links':

         if (message.token !== process.env.SLACK_TOKEN) return;

         var incomingLink = message.text,
             outgoingLink = incomingLink.replace(/\s/g, '%20');

         slashCommand.replyPublic(message, outgoingLink);

      break;
      default:
         slashCommand.replyPrivate(message, "I'm afraid I don't know how to " + message.command + " yet.");
   }
});
```

**Comment by ShaneHowell** [comment] 2017-01-13 13:32
I did some more reading and it appears I found the answer to the above but it's now causing another issue.

I changed the above from a `replyPublic` to a `replyPublicDelayed` because of [this snippet](https://api.slack.com/slash-commands#responding_to_a_command) from the Slack docs:

> The only user-facing difference between immediate responses and delayed responses is that "in channel" delayed responses will not include the initial command sent by the user. To echo the command back to the channel, you'll still need to provide a response to Slack's original visit to your invocation URL.

So now what I have is:
```
controller.on('slash_command', function (slashCommand, message) {
   switch (message.command) {
      case '/links':

         if (message.token !== process.env.SLACK_TOKEN) return;

         var incomingLink = message.text,
             outgoingLink = incomingLink.replace(/\s/g, '%20');

         slashCommand.replyPublicDelayed(message, "", function() {
           slashCommand.replyPublicDelayed(message, outgoingLink);
         });

      break;
      default:
         slashCommand.replyPrivate(message, "I'm afraid I don't know how to " + message.command + " yet.");
   }
});
```

Which this works and removes the original slash command request from posting but produces a `slackbot` error message even though the message returns:
<img width="513" alt="screen shot 2017-01-13 at 8 30 25 am" src="https://cloud.githubusercontent.com/assets/5295741/21931670/af74b23e-d96a-11e6-99af-36333e0c7ab7.png">

Can anyone shed some light as to why this is happening and how I would go about to fix it?

**Comment by ShaneHowell** [comment] 2017-01-13 15:08
I've debugged this even more now and it appears that adding
`slashCommand.replyPrivate(message, ' ');`
above the `replyPublicDelayed` line prevents the Slack timeout message.

I'm not versed enough in the API's to know if this is intended or bug though.

**Comment by ShaneHowell** [comment] 2017-01-13 15:31
I've debugged this even more now and it appears that adding
slashCommand.replyPrivate(message, ' ');
above the replyPublicDelayed line prevents the Slack timeout message.

I'm not versed enough in the API's to know if this is intended or a bug though.

**Comment by robbawebba** [comment] 2017-01-13 17:34
@ShaneHowell After sifting through the documentation, I noticed that the timeout for responses is 3000ms. when using delayed responses, you might be exceeding that timeout limit. Here's Slack's suggestion from [this site](https://api.slack.com/slash-commands#responding_to_a_command):
>If you don't want to respond with any message or would rather send your responses later using delayed responses, you should still respond to the invocation of your URL with a simple HTTP 200.

That's why the timeout doesn't occur if you use `replyPrivate` first, since it fulfills the time restriction. 

To create delayed responses (responses after 3000ms have passed), Slack provides some nice instructions on how to do this in the subsection `Delayed responses and multiple responses` in the link I posted above. Hope this helps!

**Comment by ShaneHowell** [comment] 2017-01-13 17:43
@robbawebba Thanks for the help! That's the conclusion I eventually ended up on but it doesn't really make sense to me. 

The response from the slash command is pretty much instant so it is more than fulfilling the time restraint for the delay, but it still produces the `timeout` if I don't send the `replyPrivate` beforehand.

**Comment by robbawebba** [comment] 2017-01-13 18:11
@ShaneHowell that's really strange. So you're definitely responding within 3 seconds, and it still produces the timeout error?

**Comment by ShaneHowell** [comment] 2017-01-13 18:19
@robbawebba Correct. 

This was my original attempt that produces the timeout, even with the response being almost instant:
```
controller.on('slash_command', function (slashCommand, message) {
   switch (message.command) {
      case '/links':

         if (message.token !== process.env.SLACK_TOKEN) return;

         var incomingLink = message.text,
             outgoingLink = incomingLink.replace(/\s/g, '%20');

         slashCommand.replyPublicDelayed(message, outgoingLink);

      break;
      default:
         slashCommand.replyPrivate(message, "I'm afraid I don't know how to " + message.command + " yet.");
   }
});
```

And this is what I ended up with to prevent the `timeout`, which works, but doesn't seem right having to send an empty `replyPrivate` to prevent it:
```
controller.on('slash_command', function (slashCommand, message) {
   switch (message.command) {
      case '/links':

         if (message.token !== process.env.SLACK_TOKEN) return;

         var incomingLink = message.text,
             outgoingLink = incomingLink.replace(/\s/g, '%20');

         if (outgoingLink) {
            slashCommand.replyPrivate(message, ' ');
            slashCommand.replyPublicDelayed(message, outgoingLink);
         } else {
            slashCommand.replyPrivate(message, "Something went wrong.");
         }

      break;
      default:
         slashCommand.replyPrivate(message, "I'm afraid I don't know how to " + message.command + " yet.");
   }
});
```

**Comment by robbawebba** [comment] 2017-01-13 19:57
@ShaneHowell I think I found it! Check out [this little function](https://github.com/howdyai/botkit/blob/master/readme-slack.md#botreplyacknowledge) from the botkit docs. This may be what you are looking for. Instead of using `replyPrivate()`, replace it with `slashCommand.replyAcknowledge()` to sent the HTTP 200 response that Slack suggests in [their docs](https://api.slack.com/slash-commands#responding_to_a_command). After that, you should be good to use `replyPublicDelayed()` as expected.

**Comment by danhodkinson** [comment] 2017-04-15 15:20
@robbawebba @ShaneHowell did you manage to get this working?
Even with replyAcknowledge i still get the timeout error even though the message has successfully sent. It's very strange.

**Comment by robbawebba** [comment] 2017-04-15 20:13
@danhodkinson Have you tried the suggestion in the comment above yours? I think that might solve your issue! 😄 Please let us know if it works or not so we can close this issue or keep working for a solution

**Comment by danhodkinson** [comment] 2017-04-15 21:34
@robbawebba i have.
This is what i'm currently running:
`controller.on('slash_command', function (slashCommand, message) {

    switch (message.command) {
        case "/question": //handle the `/echo` slash command. We might have others assigned to this app too!
            // The rules are simple: If there is no text following the command, treat it as though they had requested "help"
           
            if (message.token !== verificationToken) return; //just ignore it.
            slashCommand.replyAcknowledge();
            slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text);

            break;
        default:
            slashCommand.replyPublic(message, "I'm afraid I don't know how to " + message.command + " yet.");

    }
})`

The message still sends but i get the timeout error on the first message. and every message i send re-appears in the input box as if it hasn't sent.

**Comment by robbawebba** [comment] 2017-04-15 22:03
@danhodkinson Thanks for your feedback! I just dug through the botkit source and there may be an issue with the implementation of `replyAcknowledge()`. To debug the issue, do you mind sharing a link to your slackbot with me if it's on GitHub? I don't have a slash commands bot to run locally. If your work is not on GitHub or you don't want to share it no worries! I can try and create one.

**Comment by danhodkinson** [comment] 2017-04-15 22:05
@robbawebba interesting. my work is all local through ngrok at the moment whilst i test but i'm happy to send you my file as it's basically just echoing out what i'm entering as the text on the command for now whilst i get to grips with botkit.

**Comment by robbawebba** [comment] 2017-04-15 22:18
@danhodkinson Sweet, feel free to copy/paste it here in a ```code block``` comment or email it to me at robertweber95@gmail.com 🙂

**Comment by danhodkinson** [comment] 2017-04-15 22:21
@robbawebba here you go.
```
var clientId = CLIENTID;
var clientSecret = CLIENTSECRET;
var verificationToken = VERIFICATIONTOKEN;

/* Uses the slack button feature to offer a real time bot to multiple teams */
var Botkit = require('botkit');

/*to run through node with ngrok or similar running: e.g. PORT=4390 node index.js*/

if (!clientId || !clientSecret || !PORT || !verificationToken) {
    console.log('Error: Specify CLIENT_ID, CLIENT_SECRET, VERIFICATION_TOKEN and PORT in environment');
    process.exit(1);
}

var config = {}
if (process.env.MONGOLAB_URI) {
    var BotkitStorage = require('botkit-storage-mongo');
    config = {
        storage: BotkitStorage({mongoUri: process.env.MONGOLAB_URI}),
    };
} else {
    config = {
        json_file_store: './db_slackbutton_slash_command/',
    };
}

var controller = Botkit.slackbot(config).configureSlackApp(
    {
        clientId: clientId,
        clientSecret: clientSecret,
        scopes: ['commands'],
    }
);

controller.setupWebserver(process.env.PORT, function (err, webserver) {
    controller.createWebhookEndpoints(controller.webserver);

    controller.createOauthEndpoints(controller.webserver, function (err, req, res) {
        if (err) {
            res.status(500).send('ERROR: ' + err);
        } else {
            res.send('Success!');
        }
    });
});

controller.on('slash_command', function (slashCommand, message) {

    switch (message.command) {
        case "/question": 
            
            if (message.token !== verificationToken) return; //just ignore it.
           
            slashCommand.replyAcknowledge();
            slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text);
            break;
        default:
            slashCommand.replyPublic(message, "I'm afraid I don't know how to " + message.command + " yet.");

    }
});
```

**Comment by robbawebba** [comment] 2017-04-17 16:09
@danhodkinson Sorry for the delay! I finally got around to tinkering with the issue and I think I've found an answer. 

The first thing I tried was just calling `slashCommand.replyAcknowledge()` by itself with no subsequent reply. This worked as expected and sent the status 200 response to slack. next, I tried your code that includes the `slashCommand.replyAcknowledge()` followed by `slashCommand.replyPublicDelayed()`. This **didn't work**, which I found pretty odd. Here's how I was able to solve the issue:

```
slashCommand.replyAcknowledge(function(){});
slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text);
```

The  only difference here was adding the empty callback function inside `replyAcknowledge()`. Luckily this worked! If you could give this fix a try and let me know how that works, that would be super helpful 😄

**Comment by danhodkinson** [comment] 2017-04-18 20:42
@robbawebba i receive the following error when attempting to use your method:
`typeError: slashCommand.replyAcknowledge is not a function`

**Comment by robbawebba** [comment] 2017-04-18 20:43
Could you paste more code? Just to see what you're doing. When I get to my
computer I'll share with you the code I used.

**Comment by danhodkinson** [comment] 2017-04-18 20:48
```
controller.on('slash_command', function (slashCommand, message) {

    switch (message.command) {
        case "/question": 
            // Otherwise just echo back to them what they sent us.
            
            // but first, let's make sure the token matches!
            if (message.token !== verificationToken) return; //just ignore it.

            // if no text was supplied, treat it as a help command
            if (message.text === "" || message.text === "help") {
                slashCommand.replyPrivate(message,
                    "I echo back what you tell me. " +
                    "Try typing `/question hello` to see.");
                return;
            }

            // If we made it here, just echo what the user typed back at them
            slashCommand.replyAcknowledge(function(){});
            slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text);
            break;

        default:
            slashCommand.replyPublic(message, "I'm afraid I don't know how to " + message.command + " yet.");
    }

});
```

**Comment by robbawebba** [comment] 2017-04-19 23:04
I'm unable to reproduce it unfortunately. Try printing the `slashCommand` object to see it's properties and to see if `replyAcknowledge` is among those properties. 

Here's the code I'm using, which is pretty similar to your code:
```
controller.on('slash_command', function (slashCommand, message) {

    switch (message.command) {
        case "/foodme": //handle the `/foodme` slash command. We might have others assigned to this app too!

            // /foodme help displays this message
            if (message.text === "help") {
              slashCommand.replyPrivate(message, "Foodme is a Slack command" +
                " that helps you find something to eat. Just type `/foodme`" +
                " to start.")
              break;
            }

            // Let's make sure the token matches. No imposters allowed!
            if (message.token !== process.env.VERIFICATION_TOKEN) return; //just ignore it.

            slashCommand.replyAcknowledge(function(){});
            slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text);

        default:
            slashCommand.replyPublic(message, "I'm sorry " + message.user +
                ", I'm afraid I can't do that. :robot_face:");

    }

});
```

**Comment by danhodkinson** [comment] 2017-04-20 10:18
@robbawebba interesting. i'll try with that code as it is a little later today and let you know the results.

**Comment by apmoronez** [comment] 2017-04-25 21:52
I've noticed this happening to me as well.  I have a control loop that goes something like: `slash_command` -> `replyPrivate` (with interactive buttons attachments) -> `replyInteractive` (from button presses).  I notice that when I use `replyInteractive` to initially respond to the `slash_command` event, I get a quick initial response, following by the "timeout" error message later (after 3 seconds), whereas if I use `replyPrivate`, I have no issues.  Looking around I have a feeling it's related to how `replyPrivate` uses a simple `bot.res.json()` call to respond, whereas `replyInteractive` (and the delayed versions of the Public/Private reply functions) initiate a `request` call (which works as far as posting into slack, but doesn't tell the requester that anything happened, apparently).

What's strange is that I don't see the faulty timeout behavior when using `replyInteractive` to respond to successive `interactive_message_callback` events.  So `request` mechanism works, just not when responding to `slash_command` messages.

**Closed** 2018-05-15 18:01 UTC
Labels: Slack-related, help wanted
