### ISSUE TITLE
Need help setting up Botkit on Azure

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1004] opened 2017-09-07 11:29 UTC
app.js

var Botkit = require('botkit');
var controller = Botkit.botframeworkbot({
});

var bot = controller.spawn({
appId: '5e1a87ee-9253-4c11-8a78-62513f5bdd9d',
appPassword: 'W0bS9NAJHQo9aXbbqD4sW4w'
});

// if you are already using Express, you can use your own server instance...
// see "Use BotKit with an Express web server"
controller.setupWebserver(process.env.port||3000,function(err,webserver) {
controller.createWebhookEndpoints(controller.webserver, bot, function() {
console.log('This bot is online!!!');
});
});

// user said hello
controller.hears(['hello'], 'message_received', function(bot, message) {

bot.reply(message, 'Hey there.');
});

controller.hears(['cookies'], 'message_received', function(bot, message) {

bot.startConversation(message, function(err, convo) {

    convo.say('Did someone say cookies!?!!');
    convo.ask('What is your favorite type of cookie?', function(response, convo) {
        convo.say('Golly, I love ' + response.text + ' too!!!');
        convo.next();
    });
});
});

package.json
{
"name": "botkitresetbot",
"version": "1.0.0",
"description": "",
"main": "app.js",
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"author": "",
"license": "ISC",
"dependencies": {
"botkit": "^0.5.8",
"restify":"^5.2.0",
"botbuilder":"^3.9.1",
"os":"0.1.1",
"command-line-args":"4.0.7",

}
}

**Comment by Yulgana33** [comment] 2017-09-07 11:29
Can you please help me how to publish bot kit - Botframework as app service on Azure and what could be endpoint URL. As I wanted to run bot on skype.. It is easy to deploy botbuilder node js bot on azure

**Comment by peterswimm** [comment] 2017-09-07 13:11
duplicate of #999

**Comment by peterswimm** [comment] 2017-09-07 13:13
Seems similar to the problems #1003 is having, take a look there.

**Comment by benbrown** [comment] 2017-09-18 21:25
@Yulgana33 you need to immediately invalidate the appId and app secret you included in the code above.

**Closed** 2017-09-19 20:31 UTC
