### ISSUE TITLE
Slack Verification Token for interactive messages and events

### ISSUE THREAD

**Issue by shishirsharma** [howdyai/botkit#967] opened 2017-08-24 08:18 UTC
Slack specifies a Verification Token for interactive messages and events api. Botkit does not support this out of the box. 

This can't be handled via checking for `req.body.token` in `createWebhookEndpoints` callback, as events get triggered before the call of callback. Also `cb` does not have `req`.

**Comment by shishirsharma** [comment] 2017-08-24 08:18
If this check makes sense, I am willing to open a PR.

**Comment by peterswimm** [comment] 2017-08-24 18:35
duplicate of https://github.com/howdyai/botkit/issues/966

**Closed by peterswimm** 2017-08-24 18:35 UTC

**Comment by shishirsharma** [comment] 2017-09-04 09:58
https://github.com/howdyai/botkit/pull/981
