### ISSUE TITLE
Connection Continously Fails With New Version

### ISSUE THREAD

**Issue by anurag-saran** [howdyai/botkit#809] opened 2017-04-28 08:48 UTC
## The connection continuously keeps failing. See error log Below:
```
anurags-MBP-2:keyforth_slack anuragsaran$ node server.js 
Initializing Botkit v0.5.3
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: comradely ...attempting to connect to RTM!
notice: RTM websocket opened
notice: RTM close event: 1006 : 
error: Abnormal websocket close event, attempting to reconnect
notice: ** BOT ID: comradely ...reconnect attempt #1 of null being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: comradely ...attempting to connect to RTM!
notice: RTM websocket opened
notice: RTM close event: 1006 : 
error: Abnormal websocket close event, attempting to reconnect
notice: ** BOT ID: comradely ...reconnect attempt #1 of null being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: comradely ...attempting to connect to RTM!
notice: RTM websocket opened
notice: RTM close event: 1006 : 
error: Abnormal websocket close event, attempting to reconnect
notice: ** BOT ID: comradely ...reconnect attempt #1 of null being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: comradely ...attempting to connect to RTM!
notice: RTM websocket opened
notice: RTM close event: 1006 : 
```

## With Debug : true
```
notice: ** BOT ID: comradely ...attempting to connect to RTM!
notice: RTM websocket opened
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO undefined undefined
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO undefined undefined
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO U55SGQWF5 undefined
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
notice: RTM close event: 1006 : 
error: Abnormal websocket close event, attempting to reconnect
notice: ** BOT ID: comradely ...reconnect attempt #1 of null being made after 1000ms
debug: rtm.start { no_unreads: true,
  simple_latest: true,
```

**Comment by anurag-saran** [comment] 2017-04-28 08:52
I am seeing this issue with  "botkit": "^0.5.1" and  "botkit": "^0.5.0" versions too.

**Comment by harveyr** [comment] 2017-04-28 14:33
Same here. I dropped back to 0.5.2 and it fixed the issue.

**Comment by peterswimm** [comment] 2017-04-28 15:24
Duplicate of https://github.com/howdyai/botkit/issues/806 Should have a fix for this this morning!

**Closed by peterswimm** 2017-04-28 15:24 UTC
