### ISSUE TITLE
delete method is not required in custom storage 

### ISSUE THREAD

**Issue by davidwneary** [howdyai/botkit#658] opened 2017-02-15 14:13 UTC
Not sure if this is an issue or a deliberate choice but it seems strange to me that custom storage options don't need to have a `delete` method. This just tripped me up when I was migrating from using simple storage (which has a delete method) and mongodb store. 

My use case is that when I get an `account_invalid` response when attempting to start an RTM connection I want to delete the team from my records since they have uninstalled the app.

**Comment by peterswimm** [comment] 2017-07-05 20:16
https://github.com/howdyai/botkit/issues/682 duplicate of

**Closed by peterswimm** 2017-07-05 20:16 UTC
Labels: question, storage
